name: Android CI

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE
  pull_request:
    branches: [ develop ]
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Check Android dependencies of the project
      run: ./gradlew androidDependencies

    - name: Assemble with debug
      run: ./gradlew assembleDebug

    - name: unit test with debug coverage report
      run: ./gradlew test createDebugCoverageReport --stacktrace

    - name: Upload test artifacts and results
      uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: results
        path: |
          **/build/reports/tests/**/*
          **/build/reports/androidTest/**/*
          **/build/reports/coverage/**/*
        if-no-files-found: warn
        retention-days: 14

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run static code inspection
        run: ./gradlew lint

      - name: Upload results Artifact
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: results
          path: |
            **/build/reports/lint-results.html
            **/build/reports/lint-results.xml
          if-no-files-found: error
          retention-days: 14